

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LayoutComponent from "../components/LayoutComponent";
import { useParams } from "next/navigation";
import { ClerkProvider } from "@clerk/nextjs";
import { Suspense } from "react";
import Loading from "./loading";
import ContextAPI from "@/components/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Leetcode",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ContextAPI>  
      <ClerkProvider>  <LayoutComponent>{children}</LayoutComponent> </ClerkProvider>
      
      </ContextAPI>
      </body>
    </html>
  );
}