import type { Metadata } from "next";
import {Work_Sans} from "next/font/google";
import "./globals.css";
import LayoutComponent from "../components/LayoutComponent";
import { useParams } from "next/navigation";
import { ClerkProvider } from "@clerk/nextjs";
import { Suspense } from "react";
import Loading from "./loading";
import ContextAPI from "@/components/context";

const inter =   Work_Sans({weight:'400', subsets:['latin']});

export const metadata: Metadata = {
  title: "Algominds",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextAPI>
          <ClerkProvider>
            {" "}
            <LayoutComponent>{children}</LayoutComponent>{" "}
          </ClerkProvider>
        </ContextAPI>
      </body>
    </html>
  );
}
